File buildLog = new File( basedir, 'build.log')
assert buildLog.exists()

def final log = buildLog.getText()
String ps = File.separator
assert log.contains("com" + ps + "google" + ps + "guava" + ps + "guava" + ps + "13.0.1" + ps + "guava-13.0.1.jar")
assert log.contains("com" + ps + "terracotta" + ps + "security-keychain" + ps + "1.3.1" + ps + "security-keychain-1.3.1.jar")
assert log.contains("com" + ps + "terracottatech" + ps + "search" + ps + "1.3.0" + ps + "search-1.3.0.jar")
assert log.contains("commons-cli" + ps + "commons-cli" + ps + "1.1" + ps + "commons-cli-1.1.jar")
assert log.contains("commons-collections" + ps + "commons-collections" + ps + "3.2.1" + ps + "commons-collections-3.2.1.jar")
assert log.contains("commons-io" + ps + "commons-io" + ps + "2.4" + ps + "commons-io-2.4.jar")
assert log.contains("commons-lang" + ps + "commons-lang" + ps + "2.0" + ps + "commons-lang-2.0.jar")
assert log.contains("commons-logging" + ps + "commons-logging" + ps + "1.0.3" + ps + "commons-logging-1.0.3.jar")
assert log.contains("concurrent" + ps + "concurrent" + ps + "1.3.4" + ps + "concurrent-1.3.4.jar")
assert log.contains("gf-3122" + ps + "gf.asm" + ps + "3.1.0" + ps + "gf.asm-3.1.0.jar")
assert log.contains("gf-3122" + ps + "gf.jackson-core-asl" + ps + "1.9.2" + ps + "gf.jackson-core-asl-1.9.2.jar")
assert log.contains("gf-3122" + ps + "gf.jackson-jaxrs" + ps + "1.9.2" + ps + "gf.jackson-jaxrs-1.9.2.jar")
assert log.contains("gf-3122" + ps + "gf.jackson-mapper-asl" + ps + "1.9.2" + ps + "gf.jackson-mapper-asl-1.9.2.jar")
assert log.contains("gf-3122" + ps + "gf.javax.annotation" + ps + "1.1" + ps + "gf.javax.annotation-1.1.jar")
assert log.contains("gf-3122" + ps + "gf.javax.mail" + ps + "1.4.4" + ps + "gf.javax.mail-1.4.4.jar")
assert log.contains("gf-3122" + ps + "gf.javax.security.auth.message" + ps + "1.0" + ps + "gf.javax.security.auth.message-1.0.jar")
assert log.contains("gf-3122" + ps + "gf.javax.servlet-api" + ps + "3.0.1" + ps + "gf.javax.servlet-api-3.0.1.jar")
assert log.contains("gf-3122" + ps + "gf.jersey-core" + ps + "1.16" + ps + "gf.jersey-core-1.16.jar")
assert log.contains("gf-3122" + ps + "gf.jersey-gf-server" + ps + "1.16" + ps + "gf.jersey-gf-server-1.16.jar")
assert log.contains("gf-3122" + ps + "gf.jersey-gf-servlet" + ps + "1.16" + ps + "gf.jersey-gf-servlet-1.16.jar")
assert log.contains("gf-3122" + ps + "gf.jersey-json" + ps + "1.16" + ps + "gf.jersey-json-1.16.jar")
assert log.contains("jline" + ps + "jline" + ps + "0.9.94" + ps + "jline-0.9.94.jar")
assert log.contains("log4j" + ps + "log4j" + ps + "1.2.17" + ps + "log4j-1.2.17.jar")
assert log.contains("net" + ps + "sf" + ps + "ehcache" + ps + "management-ehcache" + ps + "2.7.2" + ps + "management-ehcache-2.7.2.jar")
assert log.contains("net" + ps + "sf" + ps + "ehcache" + ps + "management-ehcache-impl" + ps + "2.7.2" + ps + "management-ehcache-impl-2.7.2.jar")
assert log.contains("org" + ps + "apache" + ps + "xmlbeans" + ps + "xmlbeans" + ps + "2.4.0" + ps + "xmlbeans-2.4.0.jar")
assert log.contains("org" + ps + "apache" + ps + "xmlbeans" + ps + "xmlbeans-jsr173-api" + ps + "1.0" + ps + "xmlbeans-jsr173-api-1.0.jar")
assert log.contains("org" + ps + "beanshell" + ps + "bsh" + ps + "2.0b4" + ps + "bsh-2.0b4.jar")
assert log.contains("org" + ps + "codehaus" + ps + "jackson" + ps + "jackson-xc" + ps + "1.9.2" + ps + "jackson-xc-1.9.2.jar")
assert log.contains("org" + ps + "eclipse" + ps + "jetty" + ps + "jetty-util" + ps + "8.1.7.v20120910" + ps + "jetty-util-8.1.7.v20120910.jar")
assert log.contains("org" + ps + "eclipse" + ps + "jetty" + ps + "aggregate" + ps + "jetty-all-server" + ps + "8.1.7.v20120910" + ps + "jetty-all-server-8.1.7.v20120910.jar")
assert log.contains("org" + ps + "eclipse" + ps + "jetty" + ps + "orbit" + ps + "javax.activation" + ps + "1.1.0.v201105071233" + ps + "javax.activation-1.1.0.v201105071233.jar")
assert log.contains("org" + ps + "slf4j" + ps + "slf4j-api" + ps + "1.6.6" + ps + "slf4j-api-1.6.6.jar")
assert log.contains("org" + ps + "slf4j" + ps + "slf4j-log4j12" + ps + "1.6.6" + ps + "slf4j-log4j12-1.6.6.jar")
assert log.contains("org" + ps + "terracotta" + ps + "jmxremote_optional-tc" + ps + "1.0.4" + ps + "jmxremote_optional-tc-1.0.4.jar")
assert log.contains("org" + ps + "terracotta" + ps + "management-core" + ps + "1.1.4" + ps + "management-core-1.1.4.jar")
assert log.contains("org" + ps + "terracotta" + ps + "management-tsa-war" + ps + "4.0.2" + ps + "management-tsa-war-4.0.2.war")
assert log.contains("org" + ps + "terracotta" + ps + "tc-l1-reconnect-properties" + ps + "4.1.1" + ps + "tc-l1-reconnect-properties-4.1.1.jar")
assert log.contains("org" + ps + "terracotta" + ps + "tcconfig" + ps + "4.1.1" + ps + "tcconfig-4.1.1.jar")
assert log.contains("org" + ps + "terracotta" + ps + "tcstats" + ps + "4.1.1" + ps + "tcstats-4.1.1.jar")
assert log.contains("org" + ps + "terracotta" + ps + "terracotta" + ps + "4.0.2" + ps + "terracotta-4.0.2.jar")
assert log.contains("org" + ps + "terracotta" + ps + "license" + ps + "terracotta-license" + ps + "1.0.10" + ps + "terracotta-license-1.0.10.jar")