File buildLog = new File( basedir, 'build.log' )
assert buildLog.exists()
def SLASH = File.separatorChar
def COLUMN = File.pathSeparator

def logString =  new StringBuilder().append("[DEBUG] Setting tc.tests.info.l2.classpath to: " + 
localRepositoryPath ).append(SLASH).append("net").append(SLASH).append("sf").append(SLASH).append("ehcache").append(SLASH).append("management-ehcache-impl").append(SLASH).append("2.7.2").append(SLASH).append("management-ehcache-impl-2.7.2.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("eclipse").append(SLASH).append("jetty").append(SLASH).append("orbit").append(SLASH).append("javax.servlet").append(SLASH).append("3.0.0.v201112011016").append(SLASH).append("javax.servlet-3.0.0.v201112011016.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("net").append(SLASH).append("sf").append(SLASH).append("ehcache").append(SLASH).append("management-ehcache").append(SLASH).append("2.7.2").append(SLASH).append("management-ehcache-2.7.2.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("terracotta").append(SLASH).append("management-core").append(SLASH).append("1.1.4").append(SLASH).append("management-core-1.1.4.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("com").append(SLASH).append("sun").append(SLASH).append("jersey").append(SLASH).append("jersey-core").append(SLASH).append("1.16").append(SLASH).append("jersey-core-1.16.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("com").append(SLASH).append("sun").append(SLASH).append("jersey").append(SLASH).append("jersey-servlet").append(SLASH).append("1.16").append(SLASH).append("jersey-servlet-1.16.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("com").append(SLASH).append("sun").append(SLASH).append("jersey").append(SLASH).append("jersey-server").append(SLASH).append("1.16").append(SLASH).append("jersey-server-1.16.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("asm").append(SLASH).append("asm").append(SLASH).append("3.1").append(SLASH).append("asm-3.1.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("com").append(SLASH).append("sun").append(SLASH).append("jersey").append(SLASH).append("jersey-json").append(SLASH).append("1.16").append(SLASH).append("jersey-json-1.16.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("codehaus").append(SLASH).append("jettison").append(SLASH).append("jettison").append(SLASH).append("1.1").append(SLASH).append("jettison-1.1.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("com").append(SLASH).append("sun").append(SLASH).append("xml").append(SLASH).append("bind").append(SLASH).append("jaxb-impl").append(SLASH).append("2.2.3-1").append(SLASH).append("jaxb-impl-2.2.3-1.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("javax").append(SLASH).append("xml").append(SLASH).append("bind").append(SLASH).append("jaxb-api").append(SLASH).append("2.2.2").append(SLASH).append("jaxb-api-2.2.2.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("javax").append(SLASH).append("activation").append(SLASH).append("activation").append(SLASH).append("1.1").append(SLASH).append("activation-1.1.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("codehaus").append(SLASH).append("jackson").append(SLASH).append("jackson-core-asl").append(SLASH).append("1.9.2").append(SLASH).append("jackson-core-asl-1.9.2.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("codehaus").append(SLASH).append("jackson").append(SLASH).append("jackson-mapper-asl").append(SLASH).append("1.9.2").append(SLASH).append("jackson-mapper-asl-1.9.2.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("codehaus").append(SLASH).append("jackson").append(SLASH).append("jackson-jaxrs").append(SLASH).append("1.9.2").append(SLASH).append("jackson-jaxrs-1.9.2.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("gf-3122").append(SLASH).append("gf.jersey-core").append(SLASH).append("1.16").append(SLASH).append("gf.jersey-core-1.16.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("gf-3122").append(SLASH).append("gf.jersey-gf-servlet").append(SLASH).append("1.16").append(SLASH).append("gf.jersey-gf-servlet-1.16.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("gf-3122").append(SLASH).append("gf.jersey-gf-server").append(SLASH).append("1.16").append(SLASH).append("gf.jersey-gf-server-1.16.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("gf-3122").append(SLASH).append("gf.asm").append(SLASH).append("3.1.0").append(SLASH).append("gf.asm-3.1.0.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("gf-3122").append(SLASH).append("gf.jersey-json").append(SLASH).append("1.16").append(SLASH).append("gf.jersey-json-1.16.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("gf-3122").append(SLASH).append("gf.jackson-core-asl").append(SLASH).append("1.9.2").append(SLASH).append("gf.jackson-core-asl-1.9.2.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("gf-3122").append(SLASH).append("gf.jackson-mapper-asl").append(SLASH).append("1.9.2").append(SLASH).append("gf.jackson-mapper-asl-1.9.2.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("gf-3122").append(SLASH).append("gf.jackson-jaxrs").append(SLASH).append("1.9.2").append(SLASH).append("gf.jackson-jaxrs-1.9.2.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("codehaus").append(SLASH).append("jackson").append(SLASH).append("jackson-xc").append(SLASH).append("1.9.2").append(SLASH).append("jackson-xc-1.9.2.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("terracotta").append(SLASH).append("tcconfig").append(SLASH).append("4.1.1").append(SLASH).append("tcconfig-4.1.1.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("commons-cli").append(SLASH).append("commons-cli").append(SLASH).append("1.1").append(SLASH).append("commons-cli-1.1.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("commons-lang").append(SLASH).append("commons-lang").append(SLASH).append("2.0").append(SLASH).append("commons-lang-2.0.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("commons-io").append(SLASH).append("commons-io").append(SLASH).append("2.4").append(SLASH).append("commons-io-2.4.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("concurrent").append(SLASH).append("concurrent").append(SLASH).append("1.3.4").append(SLASH).append("concurrent-1.3.4.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("log4j").append(SLASH).append("log4j").append(SLASH).append("1.2.17").append(SLASH).append("log4j-1.2.17.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("terracotta").append(SLASH).append("license").append(SLASH).append("terracotta-license").append(SLASH).append("1.0.10").append(SLASH).append("terracotta-license-1.0.10.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("beanshell").append(SLASH).append("bsh").append(SLASH).append("2.0b4").append(SLASH).append("bsh-2.0b4.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("commons-collections").append(SLASH).append("commons-collections").append(SLASH).append("3.2.1").append(SLASH).append("commons-collections-3.2.1.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("com").append(SLASH).append("google").append(SLASH).append("guava").append(SLASH).append("guava").append(SLASH).append("13.0.1").append(SLASH).append("guava-13.0.1.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("commons-logging").append(SLASH).append("commons-logging").append(SLASH).append("1.0.3").append(SLASH).append("commons-logging-1.0.3.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("slf4j").append(SLASH).append("slf4j-log4j12").append(SLASH).append("1.6.6").append(SLASH).append("slf4j-log4j12-1.6.6.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("slf4j").append(SLASH).append("slf4j-api").append(SLASH).append("1.6.6").append(SLASH).append("slf4j-api-1.6.6.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("com").append(SLASH).append("terracotta").append(SLASH).append("security-keychain").append(SLASH).append("1.3.1").append(SLASH).append("security-keychain-1.3.1.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("terracotta").append(SLASH).append("tc-l1-reconnect-properties").append(SLASH).append("4.1.1").append(SLASH).append("tc-l1-reconnect-properties-4.1.1.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("com").append(SLASH).append("terracottatech").append(SLASH).append("search").append(SLASH).append("1.3.0").append(SLASH).append("search-1.3.0.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("terracotta").append(SLASH).append("tcstats").append(SLASH).append("4.1.1").append(SLASH).append("tcstats-4.1.1.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("apache").append(SLASH).append("xmlbeans").append(SLASH).append("xmlbeans").append(SLASH).append("2.4.0").append(SLASH).append("xmlbeans-2.4.0.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("apache").append(SLASH).append("xmlbeans").append(SLASH).append("xmlbeans-jsr173-api").append(SLASH).append("1.0").append(SLASH).append("xmlbeans-jsr173-api-1.0.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("eclipse").append(SLASH).append("jetty").append(SLASH).append("aggregate").append(SLASH).append("jetty-all-server").append(SLASH).append("8.1.7.v20120910").append(SLASH).append("jetty-all-server-8.1.7.v20120910.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("eclipse").append(SLASH).append("jetty").append(SLASH).append("orbit").append(SLASH).append("javax.activation").append(SLASH).append("1.1.0.v201105071233").append(SLASH).append("javax.activation-1.1.0.v201105071233.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("eclipse").append(SLASH).append("jetty").append(SLASH).append("jetty-util").append(SLASH).append("8.1.7.v20120910").append(SLASH).append("jetty-util-8.1.7.v20120910.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("terracotta").append(SLASH).append("jmxremote_optional-tc").append(SLASH).append("1.0.4").append(SLASH).append("jmxremote_optional-tc-1.0.4.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("jline").append(SLASH).append("jline").append(SLASH).append("0.9.94").append(SLASH).append("jline-0.9.94.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("gf-3122").append(SLASH).append("gf.javax.security.auth.message").append(SLASH).append("1.0").append(SLASH).append("gf.javax.security.auth.message-1.0.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("gf-3122").append(SLASH).append("gf.javax.annotation").append(SLASH).append("1.1").append(SLASH).append("gf.javax.annotation-1.1.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("gf-3122").append(SLASH).append("gf.javax.mail").append(SLASH).append("1.4.4").append(SLASH).append("gf.javax.mail-1.4.4.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("gf-3122").append(SLASH).append("gf.javax.servlet-api").append(SLASH).append("3.0.1").append(SLASH).append("gf.javax.servlet-api-3.0.1.jar").append(COLUMN).append( 
localRepositoryPath ).append(SLASH).append("org").append(SLASH).append("terracotta").append(SLASH).append("terracotta").append(SLASH).append("4.0.2").append(SLASH).append("terracotta-4.0.2.jar").append(COLUMN)
assert 1 == buildLog.getText().count(logString)
